"""create pdf_files table

Revision ID: 25b2e995cf3a
Revises: 
Create Date: 2024-08-17 18:15:30.335938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25b2e995cf3a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pdf_files',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('content', sa.LargeBinary(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pdf_files_filename'), 'pdf_files', ['filename'], unique=False)
    op.create_index(op.f('ix_pdf_files_id'), 'pdf_files', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pdf_files_id'), table_name='pdf_files')
    op.drop_index(op.f('ix_pdf_files_filename'), table_name='pdf_files')
    op.drop_table('pdf_files')
    # ### end Alembic commands ###
