"""Add file_hash column to pdf_files

Revision ID: 7290c3301c96
Revises: 25b2e995cf3a
Create Date: 2024-08-20 17:14:47.190794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7290c3301c96'
down_revision: Union[str, None] = '25b2e995cf3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_chat_history_session_id', table_name='chat_history')
    op.drop_table('chat_history')
    op.add_column('pdf_files', sa.Column('file_hash', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'pdf_files', ['file_hash'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pdf_files', type_='unique')
    op.drop_column('pdf_files', 'file_hash')
    op.create_table('chat_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('message', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='chat_history_pkey')
    )
    op.create_index('idx_chat_history_session_id', 'chat_history', ['session_id'], unique=False)
    # ### end Alembic commands ###
