"""add session_id as foreign key to PDFFile model

Revision ID: d0fe40c85905
Revises: 7290c3301c96
Create Date: 2024-08-20 19:01:46.479388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd0fe40c85905'
down_revision: Union[str, None] = '7290c3301c96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_chat_history_session_id', table_name='chat_history')
    op.drop_table('chat_history')
    op.add_column('pdf_files', sa.Column('session_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_pdf_files_session_id'), 'pdf_files', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pdf_files_session_id'), table_name='pdf_files')
    op.drop_column('pdf_files', 'session_id')
    op.create_table('chat_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('message', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='chat_history_pkey')
    )
    op.create_index('idx_chat_history_session_id', 'chat_history', ['session_id'], unique=False)
    # ### end Alembic commands ###
