"""add session_id as foreign key to PDFFile model2

Revision ID: d8df2f27a034
Revises: d0fe40c85905
Create Date: 2024-08-20 19:03:58.166922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8df2f27a034'
down_revision: Union[str, None] = 'd0fe40c85905'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pdf_files_session_id', table_name='pdf_files')
    op.create_unique_constraint(None, 'pdf_files', ['session_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pdf_files', type_='unique')
    op.create_index('ix_pdf_files_session_id', 'pdf_files', ['session_id'], unique=False)
    # ### end Alembic commands ###
